### PR TITLE
Add support for Proscenic air purifier (tested against Proscenic A8) addresses #363 and #195

### PR DESCRIPTION
**Pull request by ak6i**
This addresses #363 to add full support for the Proscenic A8 air purifier:
* switch on and off
* manual and automatic mode
* speed slider sets to one of the three modes and disables automatic mode

The following functionality is not supported:
* countdown timer
* enable/disable the air quality light (retains manufacturer functionality: sleep mode = light off; all other power on modes = light on)

The following functionality is untested:
* child lock
* air purifiers other than the Proscenic A8 (but from an examination of the code I do not believe there will be any regression issues)

There is one, pre-existing, known issue:
* there is a "Mode" toggle that mirrors the power-on state.  This is present for all air purifiers.

This code contains a tweak to the handling of DP_SWITCH - I observed #195 with the Proscenic A8, and I believe the new logic should address it for all.  It also contains a fix for retrieving the PM2.5 value - this looked like a bug that was always there.

When building and running against my local Homebridge I found that there were some issues in AirConditionerAccessory.js and index.js.  This PR does *not* contain those fixes so that this change can be applied on any branch.

### CODE REVIEW

**Comment by fate8383** [comment]
this is excellent, I inserted to lib folder and for siguro air purifier and solve most of my problems, but I still get [12/10/2022, 2:27:46 PM] [homebridge-tuya] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
this warnings, no matter what I have looked at it is still warning, device info has this:
"code": "fan_speed_enum",
"mode": "rw",
"type": "Enum",
"property": {
"range": [
"auto",
"sleep"

so there are 5 speeds 1-2-3-auto-sleep, where should I change the code to avoid this error? I am not really interested in the using the fan speed but if I can avoid the error that would be great, of course if I can use fan speed also better but you know what I mean. Thanks a lot @ak6i

**Comment by ak6i** [comment]
@fate8383 Awesome! Please feel free to submit a PR with your changes.

**Comment by 05TEVE** [comment]
Hi @fate8383 , If you can create a PR with your changes i can get this into 3.1.1 Release :)

**Comment by 05TEVE** [comment]
I have taken the files from @fate8383 and pushed them as part of 3.1.1-beta.10. @ak6i, are you able to test with this version and config everything looks good from your side?

**Comment by ak6i** [comment]
@05TEVE I've updated this PR to merge the Proscenic support I implemented with the Siguro support from @fate8383 ( and also remove the doorbell support I was working on).  Probably all you need from this is the AirPurifierAccessory.js file.

Offtopic: once this PR is merged, I could take another look at the doorbell support.  It's not great (even Home Assistant doesn't support Tuya video devices) but at least I managed to make it send a snapshot of who rang the doorbell!

**Review by 05TEVE — APPROVED** [review]
LGTM!

**Comment by 05TEVE** [comment]
Hi @ak6i,

I have merged the PR into 3.1.1 and pushed it live with version 3.1.1-beta.12.
Please have a test and let me know if there are any issues.

**Comment by 05TEVE** [comment]
Hi @ak6i, 
If you have changes to add even basic doorbell support that would be a really nice addition! :)

**Comment by ak6i** [comment]
> Hi @ak6i, If you have changes to add even basic doorbell support that would be a really nice addition! :)

[Here's the commit with basic support](https://github.com/ak6i/homebridge-tuya/commit/7db7a1f12bceb03405ef7d1fbbb3c6fffdc2b30c).  When someone rings the doorbell, you'll get a notification "Someone rang the doorbell." with the picture that was taken.  The video stream doesn't work (the means to authenticate with Tuya is too much of a PITA to implement) so you'll always see the last picture that was taken when you go to that camera in the Home app, and there's no audio so you can neither hear nor talk to them.  But at least you get a picture so it's easy to ignore callers you don't want to answer  ;)

Also, I have only tested it on the Virone VDP-65.  As with all Tuya stuff, other manufacturers may implement things differently.  But feel free to try it out.  And sorry for the delay in replying!

**Comment by 05TEVE** [comment]
Hi @ak6i, these changes look good for the Doorbell. Would it be possible for you to raise another PR with the changes for the Doorbell into the 3.1.2 Branch?

**Pull request merged**
