### PR TITLE
Added LightbulbAccessory supporting on/off, dimming, color temperature, and RGB custom color

### PR DESCRIPTION
**Pull request by zysoft**
Added LightbulbAccessory supporting on/off, dimming, color temperature, and RGB custom color
Updated documentation to reflect the changes.

Tested on:
- [Feit Electric BPA800/RGBW/AG/2](https://www.feit.com/products/bulbs/smart-wifi-light-bulb/smart-wifi-bulb-color-changing-tunable-white/)
- [Phoenix Shine Smart WiFi Bulb GU10 5W](https://www.amazon.com/gp/product/B07F696KYD/). (Tuya app identifies it as "Tellur smart bulb" for some reason).

### CODE REVIEW

**Comment by zysoft** [comment]
Forgot to mention that both test lightbulbs worked with default settings, no options needed.

**Comment by codetheweb** [comment]
Wow, thanks for all your great work @zysoft.  Just took a quick glance through the code, and it looks pretty good.
One question so far: I noticed you created a `setMany()` function.  ~~TuyAPI should support something similar natively.~~  I guess it doesn't, I thought I had included that capability.  I'll look into adding it.

@J4YRY4N @Fabinewchurch @albertsal would appreciate it if you guys could test this.

**Comment by zysoft** [comment]
Thank you @codetheweb! 
I looked through the docs and didn't find anything similar. Would be cool having that in TuyAPI.

**Comment by zysoft** [comment]
Sure, no problem at all. 
Please take a look at the code and let me know if you want anything else changed. I'll then go and do all changes at once.

**Comment by codetheweb** [comment]
Hey @zysoft would appreciate it if you could take a look at the changes I made.

Things left to do:

- [ ] Add multi-set to TuyAPI
- [ ] Switch this to using that multi-set function
- [ ] Update README

Finally, do you think the `dimmable` device is now redundant as the lightbulb device can be configured to act as a dimmer switch?

**Comment by codetheweb** [comment]
Ok, that makes sense.

I changed the code to use the new `multiple` set feature of TuyAPI, however I can't get it to work with your `this.updateCallback` concept (it currently works, just a little laggy because I'm using `callback()` directly).

I'm done for tonight, but if you want to look at it sometime soon that would be much appreciated.

**Comment by zysoft** [comment]
Sorry man, don't have time to work on that now. The concept behind the `updateCallback` is simple. We remember the callback method which needs to be called, and if another change comes in rapidly, before we actually send the data out by timer, the previous callback is executed directly, so HomeKit doesn't wait, and the next callback is saved in `updateCallback`. When timer actually fires, it gets the last saved callback and passes it as a callback method to TuyAPI along with the list of commands to execute.

I think something like this might work:

```javascript
 scheduleChange(callback) {
    clearTimeout(this.updateTimer);
    if (typeof (this.updateCallback) === 'function') {
      this.updateCallback();
    }
    this.updateCallback = callback;

    this.updateTimer = setTimeout(() => {
      const commands = this.oldState.commandsToMatch(this.currentState);
      this.oldState = this.currentState.copy();
      this.device.set({multiple: true, data: commands}).then(this.updateCallback).catch(this.updateCallback);
      this.updateCallback = null;
    }, 100);
  }
```

**Comment by codetheweb** [comment]
Got it, thanks.

**Comment by codetheweb** [comment]
(I'm copy/pasting this into every open issue and PR.)

This plugin is now deprecated, as I don't have enough time to maintain it along with other TuyAPI related projects. Please use AMoo-Miki's [homebridge-tuya-lan](https://www.npmjs.com/package/homebridge-tuya-lan) plugin instead. (Or, you can continue to use this plugin, but I will not be giving support or adding any new devices.)

I'm sorry about this, but this plugin is taking a disproportionate amount of my time that I believe is better spent making TuyAPI more stable and adding more tools to the ecosystem.

**Comment by xatrix78** [comment]
Works for me perfectly!

**Comment by iRayanKhan** [comment]
Closing: This plugin is migrating, so this code will break.

**Pull request closed without merging**
