### PR TITLE
Added support for Tuya Security Alarm

### PR DESCRIPTION
**Pull request by duculete**
Tested with blitzwolf bw-is6

HomeKit

### CODE REVIEW

**Comment by 05TEVE** [comment]
Hi @duculete, looking at this PR. Just wondering about the changes for the heater accessory that are bundled in?
Looking to pull this into the 3.1.0 release i am going to roll out in the next few weeks?

**Comment by 05TEVE** [comment]
@duculete, are you able to rebase this on the current main branch and fix the merge conflicts? I should be able to get this into a release soon once those are resolved :)

**Comment by duculete** [comment]
hi, i am not working on this anymore (no time).

**Comment by 05TEVE** [comment]
Not merging as requester is no longer working on this.

**Pull request closed without merging**
