### PR TITLE
Add oil diffuser

### PR DESCRIPTION
**Pull request by nitaybz**
Adding Oil Diffuser accessory with color changing led light

### CODE REVIEW

**Comment by Faisalthe01** [comment]
hey @nitaybz , does this also read the current humidity data and show in HomeKit from the accessory?

**Comment by nitaybz** [comment]
Nope... my machine doesn't include humidity readings

**Comment by Faisalthe01** [comment]
so it will give 0% humidity all the time and also in HomeKit status right?

**Comment by nitaybz** [comment]
Correct

**Pull request merged**
