### PR TITLE
Support for 3.4 protocol

### PR DESCRIPTION
**Pull request by tomash1**

### CODE REVIEW

**Comment by 05TEVE** [comment]
Awesome! I have tested the changes with my existing devices and everything is working as expected. 
I am going to merge this into the 3.1.1 beta and push out a version for testing.

**Review by 05TEVE — APPROVED** [review]
LGTM

**Comment by 05TEVE** [comment]
Hi @tomash1,

I have merged this into 3.1.1 and released version 3.1.1-beta.12 with the changes. Thanks heaps for your contribution!

**Comment by dropbeardevs** [comment]
Oh my goodness. I installed 3.1.1 beta and it worked with my 3.4 bulb!!! I've been waiting a very long time for this (I tried implementing protocol 3.4 myself but got nowhere).

Thank you so much @tomash1 and @05TEVE!!!

**Pull request merged**
